feat(deployment-update workflow): Input validation

diff --git a/.github/workflows/deployment-update.yaml b/.github/workflows/deployment-update.yaml
--- a/.github/workflows/deployment-update.yaml
+++ b/.github/workflows/deployment-update.yaml
@@ -28,6 +28,20 @@ jobs:
       BRANCH: deployment-update-${{ inputs.deployment }}-${{ inputs.version }}
 
     steps:
+      - name: Validate inputs
+        run: |
+          # Check if the version is in the format x.y.z
+          if [[ ! ${{ inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format. Please provide a version in the format x.y.z"
+            exit 1
+          fi
+
+          # Check if the deployment is either 'api' or 'frontend'
+          if [[ ${{ inputs.deployment }} != "api" && ${{ inputs.deployment }} != "frontend" ]]; then
+            echo "Invalid deployment. Please provide either 'api' or 'frontend'"
+            exit 1
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
